### ISSUE TITLE
Incorrectly appending to wrong cm-gutter column?

### ISSUE THREAD

**Issue by itsonlyjames** [nadavspi/obsidian-relative-line-numbers#33]
There seems to be two columns of `cm-gutter` and as such it puts the active line outside the list of relative line numbers, is this correct?

<img width="703" alt="Image" src="https://github.com/user-attachments/assets/53417973-f168-47e7-a237-53f666e488fc" />

**Comment by csommerl** [comment]
The same thing is happening for me, so that the plugin uses quite a bit of margin. It might be nice to have a setting to adjust padding of the line numbers.

**Comment by gursuj** [comment]
I am using this css snippet to make it visually appear in the same gutter. See this [help article](https://help.obsidian.md/snippets) on creating and enabling css snippets:

```css
.markdown-source-view.mod-cm6 .cm-gutters {
    justify-content: end;
    .cm-gutter:has(.relative-line-numbers-mono) {
        position: absolute;
        color: var(--text-normal);
    }
    .cm-lineNumbers {
        min-width: unset;
    }
}
``` 

Additionally, here's my full css snippet to make the default line number gutters more minimal too:
```css
/* See: https://docs.obsidian.md/Reference/CSS+variables/CSS+variables */

/* === begin minimal line gutter css === */
.cm-contentContainer .cm-lineNumbers .cm-gutterElement {
    padding: 0;
}
body {
    --file-folding-offset: 14px;
}
.markdown-source-view.mod-cm6 .cm-fold-indicator .collapse-indicator {
    padding-inline-end: 2px;
}
.markdown-source-view.mod-cm6 .cm-gutters {
    margin-left: -3ch;

    /* begin css specific to plugin https://github.com/nadavspi/obsidian-relative-line-numbers */
    justify-content: end;
    .cm-gutter:has(.relative-line-numbers-mono) {
        position: absolute;
        color: var(--text-normal);
    }
    .cm-lineNumbers {
        min-width: unset;
    }
    /* end css specific to plugin */
}
/* === end minimal line gutter css === */
```

Edit: Another helpful snippet for disabling line gutters in tables: https://github.com/nadavspi/obsidian-relative-line-numbers/issues/21#issuecomment-1893736939
